# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maps_printer_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mapsPrinter(object):
    def setupUi(self, mapsPrinter):
        mapsPrinter.setObjectName("mapsPrinter")
        mapsPrinter.resize(375, 355)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mapsPrinter.sizePolicy().hasHeightForWidth())
        mapsPrinter.setSizePolicy(sizePolicy)
        mapsPrinter.setMinimumSize(QtCore.QSize(320, 340))
        mapsPrinter.setSizeIncrement(QtCore.QSize(0, 0))
        mapsPrinter.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/MapsPrinter/icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mapsPrinter.setWindowIcon(icon)
        mapsPrinter.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(mapsPrinter)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(10, 12, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(mapsPrinter)
        self.checkBox.setEnabled(True)
        self.checkBox.setWhatsThis("")
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
        self.updater = QtWidgets.QPushButton(mapsPrinter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updater.sizePolicy().hasHeightForWidth())
        self.updater.setSizePolicy(sizePolicy)
        self.updater.setMinimumSize(QtCore.QSize(80, 0))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/plugins/MapsPrinter/icons/action_refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.updater.setIcon(icon1)
        self.updater.setObjectName("updater")
        self.gridLayout.addWidget(self.updater, 0, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.printBar = QtWidgets.QProgressBar(mapsPrinter)
        self.printBar.setProperty("value", 0)
        self.printBar.setObjectName("printBar")
        self.horizontalLayout.addWidget(self.printBar)
        self.exportButton = QtWidgets.QPushButton(mapsPrinter)
        self.exportButton.setObjectName("exportButton")
        self.horizontalLayout.addWidget(self.exportButton)
        self.buttonBox = QtWidgets.QDialogButtonBox(mapsPrinter)
        self.buttonBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Help)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.horizontalLayout, 8, 0, 1, 3)
        self.composerList = QtWidgets.QListWidget(mapsPrinter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.composerList.sizePolicy().hasHeightForWidth())
        self.composerList.setSizePolicy(sizePolicy)
        self.composerList.setSizeIncrement(QtCore.QSize(0, 0))
        self.composerList.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.composerList.setMouseTracking(False)
        self.composerList.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.composerList.setAcceptDrops(True)
        self.composerList.setToolTip("")
        self.composerList.setWhatsThis("")
        self.composerList.setAlternatingRowColors(True)
        self.composerList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.composerList.setResizeMode(QtWidgets.QListView.Fixed)
        self.composerList.setObjectName("composerList")
        self.gridLayout.addWidget(self.composerList, 2, 0, 1, 3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.printinglabel = QtWidgets.QLabel(mapsPrinter)
        self.printinglabel.setEnabled(True)
        self.printinglabel.setObjectName("printinglabel")
        self.horizontalLayout_6.addWidget(self.printinglabel)
        self.pageBar = QtWidgets.QProgressBar(mapsPrinter)
        self.pageBar.setProperty("value", 0)
        self.pageBar.setObjectName("pageBar")
        self.horizontalLayout_6.addWidget(self.pageBar)
        self.gridLayout.addLayout(self.horizontalLayout_6, 6, 0, 1, 3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(mapsPrinter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.formatBox = QtWidgets.QComboBox(mapsPrinter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formatBox.sizePolicy().hasHeightForWidth())
        self.formatBox.setSizePolicy(sizePolicy)
        self.formatBox.setMinimumSize(QtCore.QSize(0, 23))
        self.formatBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.formatBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.formatBox.setWhatsThis("")
        self.formatBox.setObjectName("formatBox")
        self.horizontalLayout_2.addWidget(self.formatBox)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 0, 1, 3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.path = QtWidgets.QLineEdit(mapsPrinter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.path.sizePolicy().hasHeightForWidth())
        self.path.setSizePolicy(sizePolicy)
        self.path.setSizeIncrement(QtCore.QSize(0, 0))
        self.path.setToolTip("")
        self.path.setWhatsThis("")
        self.path.setObjectName("path")
        self.horizontalLayout_3.addWidget(self.path)
        self.browser = QtWidgets.QPushButton(mapsPrinter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browser.sizePolicy().hasHeightForWidth())
        self.browser.setSizePolicy(sizePolicy)
        self.browser.setMinimumSize(QtCore.QSize(100, 23))
        self.browser.setObjectName("browser")
        self.horizontalLayout_3.addWidget(self.browser)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 0, 1, 3)

        self.retranslateUi(mapsPrinter)
        self.buttonBox.rejected.connect(mapsPrinter.reject)
        QtCore.QMetaObject.connectSlotsByName(mapsPrinter)
        mapsPrinter.setTabOrder(self.checkBox, self.updater)
        mapsPrinter.setTabOrder(self.updater, self.composerList)
        mapsPrinter.setTabOrder(self.composerList, self.path)
        mapsPrinter.setTabOrder(self.path, self.browser)
        mapsPrinter.setTabOrder(self.browser, self.formatBox)
        mapsPrinter.setTabOrder(self.formatBox, self.exportButton)
        mapsPrinter.setTabOrder(self.exportButton, self.buttonBox)

    def retranslateUi(self, mapsPrinter):
        _translate = QtCore.QCoreApplication.translate
        mapsPrinter.setWindowTitle(_translate("mapsPrinter", "Maps Printer"))
        self.checkBox.setToolTip(_translate("mapsPrinter", "Check all the composers"))
        self.checkBox.setText(_translate("mapsPrinter", "Check All"))
        self.updater.setToolTip(_translate("mapsPrinter", "Update composer list"))
        self.updater.setText(_translate("mapsPrinter", "Update"))
        self.exportButton.setText(_translate("mapsPrinter", "Export"))
        self.printinglabel.setText(_translate("mapsPrinter", "Exporting..."))
        self.label.setText(_translate("mapsPrinter", "Output File Format"))
        self.formatBox.setToolTip(_translate("mapsPrinter", "Choose the output file format"))
        self.browser.setToolTip(_translate("mapsPrinter", "Choose the output folder"))
        self.browser.setText(_translate("mapsPrinter", "Br&owse..."))

