# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maps_printer_dialog_base.ui'
#
# Created: Wed Jul 30 02:06:46 2014
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_mapsPrinter(object):
    def setupUi(self, mapsPrinter):
        mapsPrinter.setObjectName(_fromUtf8("mapsPrinter"))
        mapsPrinter.resize(270, 340)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mapsPrinter.sizePolicy().hasHeightForWidth())
        mapsPrinter.setSizePolicy(sizePolicy)
        mapsPrinter.setMinimumSize(QtCore.QSize(270, 340))
        mapsPrinter.setSizeIncrement(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/MapsPrinter/icons/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mapsPrinter.setWindowIcon(icon)
        mapsPrinter.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(mapsPrinter)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.path = QtGui.QLineEdit(mapsPrinter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.path.sizePolicy().hasHeightForWidth())
        self.path.setSizePolicy(sizePolicy)
        self.path.setSizeIncrement(QtCore.QSize(0, 0))
        self.path.setToolTip(_fromUtf8(""))
        self.path.setWhatsThis(_fromUtf8(""))
        self.path.setObjectName(_fromUtf8("path"))
        self.horizontalLayout_3.addWidget(self.path)
        self.browse = QtGui.QPushButton(mapsPrinter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse.sizePolicy().hasHeightForWidth())
        self.browse.setSizePolicy(sizePolicy)
        self.browse.setMinimumSize(QtCore.QSize(100, 23))
        self.browse.setObjectName(_fromUtf8("browse"))
        self.horizontalLayout_3.addWidget(self.browse)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 2)
        self.updater = QtGui.QPushButton(mapsPrinter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updater.sizePolicy().hasHeightForWidth())
        self.updater.setSizePolicy(sizePolicy)
        self.updater.setMinimumSize(QtCore.QSize(120, 0))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/MapsPrinter/icons/action_refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.updater.setIcon(icon1)
        self.updater.setObjectName(_fromUtf8("updater"))
        self.gridLayout.addWidget(self.updater, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(mapsPrinter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.formatBox = QtGui.QComboBox(mapsPrinter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formatBox.sizePolicy().hasHeightForWidth())
        self.formatBox.setSizePolicy(sizePolicy)
        self.formatBox.setMinimumSize(QtCore.QSize(0, 23))
        self.formatBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.formatBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.formatBox.setWhatsThis(_fromUtf8(""))
        self.formatBox.setObjectName(_fromUtf8("formatBox"))
        self.horizontalLayout_2.addWidget(self.formatBox)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.exportButton = QtGui.QPushButton(mapsPrinter)
        self.exportButton.setObjectName(_fromUtf8("exportButton"))
        self.horizontalLayout.addWidget(self.exportButton)
        self.buttonBox = QtGui.QDialogButtonBox(mapsPrinter)
        self.buttonBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 2)
        self.checkBox = QtGui.QCheckBox(mapsPrinter)
        self.checkBox.setEnabled(True)
        self.checkBox.setWhatsThis(_fromUtf8(""))
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
        self.composerList = QtGui.QListWidget(mapsPrinter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.composerList.sizePolicy().hasHeightForWidth())
        self.composerList.setSizePolicy(sizePolicy)
        self.composerList.setSizeIncrement(QtCore.QSize(0, 0))
        self.composerList.setProperty(_fromUtf8("cursor"), QtCore.Qt.ArrowCursor)
        self.composerList.setMouseTracking(False)
        self.composerList.setWhatsThis(_fromUtf8(""))
        self.composerList.setAlternatingRowColors(True)
        self.composerList.setResizeMode(QtGui.QListView.Fixed)
        self.composerList.setObjectName(_fromUtf8("composerList"))
        self.gridLayout.addWidget(self.composerList, 1, 0, 1, 2)

        self.retranslateUi(mapsPrinter)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("clicked(QAbstractButton*)")), mapsPrinter.close)
        QtCore.QMetaObject.connectSlotsByName(mapsPrinter)

    def retranslateUi(self, mapsPrinter):
        mapsPrinter.setWindowTitle(QtGui.QApplication.translate("mapsPrinter", "Maps Printer", None, QtGui.QApplication.UnicodeUTF8))
        self.browse.setToolTip(QtGui.QApplication.translate("mapsPrinter", "Choose the output folder", None, QtGui.QApplication.UnicodeUTF8))
        self.browse.setText(QtGui.QApplication.translate("mapsPrinter", "Br&owse...", None, QtGui.QApplication.UnicodeUTF8))
        self.updater.setToolTip(QtGui.QApplication.translate("mapsPrinter", "Update the list below", None, QtGui.QApplication.UnicodeUTF8))
        self.updater.setText(QtGui.QApplication.translate("mapsPrinter", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("mapsPrinter", "Output File Format :", None, QtGui.QApplication.UnicodeUTF8))
        self.formatBox.setToolTip(QtGui.QApplication.translate("mapsPrinter", "Choose the output file format", None, QtGui.QApplication.UnicodeUTF8))
        self.exportButton.setText(QtGui.QApplication.translate("mapsPrinter", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setToolTip(QtGui.QApplication.translate("mapsPrinter", "Select/unselect all the composers listed below", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("mapsPrinter", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.composerList.setToolTip(QtGui.QApplication.translate("mapsPrinter", "Check the composer(s) you want to export", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
